version: '3.7'

services:
  db:
    image: postgres:11.9-alpine
    environment:
      POSTGRES_PASSWORD: bongda
      POSTGRES_USER: postgres
      POSTGRES_DB: bongda
    expose:
      - 5432
    ports:
      - 5432:5432
  redis:
    image: redis
    expose:
      - 6379
    ports:
      - 6379:6379
