version: '3.5'

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8000
    env_file:
      - ./.env
    networks:
      - reverse-proxy
#    labels:
#      - traefik.frontend.rule=Host:s1kit.com
#      - traefik.port=8000
  crawl:
    build:
      context: .
      dockerfile: crawl.Dockerfile
    env_file:
      - ./.env
    networks:
      - reverse-proxy
#    labels:
#      - traefik.frontend.rule=Host:s1kit.com
#      - traefik.port=8000
  db:
    image: postgres:10.1-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bongda
    expose:
      - 5432
    networks:
      - reverse-proxy
  redis:
    image: redis
    expose:
      - 6379
    networks:
      - reverse-proxy
networks:
  reverse-proxy:
    external: true
